[package]
name = "guessing_game"
version = "0.1.0"
authors = ["liambloom <liamrbloom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rust"
path = "magic8.rs"

[dependencies]
rand = "0.5.5"